name: Sync with git://git.suckless.org/ubase

on:
  schedule:
    - cron: '0 0 */3 * *'  # Run every 3 days at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
        ref: 'master'  # Checkout the master branch

    - name: Add git://git.suckless.org/ubase remote
      run: |
        git remote add source git://git.suckless.org/ubase

    - name: Fetch changes from git://git.suckless.org/ubase
      run: |
        git fetch source

    - name: Merge changes from git://git.suckless.org/ubase
      run: |
        git config user.name '󰬭 [CI] '
        git config user.email 'action@github.com'
        git checkout master
        git merge --allow-unrelated-histories source/master

    - name: Push changes to GitHub
      run: |
        git push origin master
